# Can one block of except statements handle multiple exception?
'''

> Yes, it is possible to handle multiple exceptions within a single try block in Python.
> When you want to catch different exceptions and handle them differently, you can use multiple except statements.
Ex.
try:
    # Your code here
except FirstException:
    handle_first_one()
except SecondException:
    handle_second_one()
'''
